// Authentication
export const USER_LOADING = 'USER_LOADING'
export const USER_LOADED = 'USER_LOADED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const AUTH_ERROR = 'AUTH_ERROR'
export const TOKEN_REFRESH_SUCCESS = 'TOKEN_REFRESH_SUCCESS'

// Errors
export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

// Diary
export const TRANSLATE_SUCCESS = 'TRANSLATE_SUCCESS'
export const TRANSLATE_FAIL = 'TRANSLATE_FAIL'
export const ADD_DIARY_POST_SUCCESS = 'ADD_DIARY_POST_SUCCESS'
export const ADD_DIARY_POST_FAIL = 'ADD_DIARY_POST_FAIL'
export const GET_DIARY_POST_SUCCESS = 'GET_DIARY_POST_SUCCESS'
export const GET_DIARY_POST_FAIL = 'GET_DIARY_POST_FAIL'
export const UPDATE_DIARY_POST_SUCCESS = 'UPDATE_DIARY_POST_SUCCESS'
export const UPDATE_DIARY_POST_FAIL = 'UPDATE_DIARY_POST_FAIL'
export const DELETE_DIARY_POST_SUCCESS = 'DELETE_DIARY_POST_SUCCESS'
export const DELETE_DIARY_POST_FAIL = 'DELETE_DIARY_POST_FAIL'

// Friends
export const USER_SEARCH_SUCCESS = 'USER_SEARCH_SUCCESS'
export const USER_SEARCH_FAIL = 'USER_SEARCH_FAIL'
export const ISSUE_FRIEND_REQUEST_SUCCESS = 'ISSUE_FRIEND_REQUEST_SUCCESS'
export const ISSUE_FRIEND_REQUEST_FAIL = 'ISSUE_FRIEND_REQUEST_FAIL'
export const GET_FRIEND_REQUESTS_ISSUED_BY_ME_SUCCESS = 'GET_FRIEND_REQUESTS_ISSUED_BY_ME_SUCCESS'
export const GET_FRIEND_REQUESTS_ISSUED_BY_ME_FAIL = 'GET_FRIEND_REQUESTS_ISSUED_BY_ME_FAIL'
export const GET_FRIEND_REQUESTS_ISSUED_TO_ME_SUCCESS = 'GET_FRIEND_REQUESTS_ISSUED_TO_ME_SUCCESS'
export const GET_FRIEND_REQUESTS_ISSUED_TO_ME_FAIL = 'GET_FRIEND_REQUESTS_ISSUED_TO_ME_FAIL'
export const RESPOND_TO_PENDING_FRIEND_REQUEST_SUCCESS = 'RESPOND_TO_PENDING_FRIEND_REQUEST_SUCCESS'
export const RESPOND_TO_PENDING_FRIEND_REQUEST_FAIL = 'RESPOND_TO_PENDING_FRIEND_REQUEST_FAIL'